SELECT 
    ROUTE_ID,
    OBJECT_NUM,
    START_TIME,
    END_TIME,
    EXTRACT(EPOCH FROM (END_TIME - START_TIME)) / 60 AS OPERATION_TIME,
    CASE 
        WHEN EXTRACT(EPOCH FROM (END_TIME - START_TIME)) / 60 > AVG(EXTRACT(EPOCH FROM (END_TIME - START_TIME)) / 60) OVER (PARTITION BY ROUTE_ID) THEN 1
        ELSE 0
    END AS CASE_1,
    CASE 
        WHEN EXTRACT(EPOCH FROM (END_TIME - START_TIME)) / 60 > LAG(avg_operation_time, 3) OVER (PARTITION BY ROUTE_ID ORDER BY OBJECT_NUM) THEN 1
        ELSE 0
    END AS CASE_2
FROM (
    SELECT 
        ROUTE_ID,
        OBJECT_NUM,
        START_TIME,
        END_TIME,
        AVG(EXTRACT(EPOCH FROM (END_TIME - START_TIME)) / 60) OVER (PARTITION BY ROUTE_ID ORDER BY OBJECT_NUM ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING) AS avg_operation_time
    FROM OPERATIONS
) AS subquery;
